docker_username: llexx
docker_image: llexx/devops-example-app
pub_key_path: "/Users/alex/.ssh/id_rsa.pub"
datadog_site: "datadoghq.com"
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: Application health check status
        url: "http://localhost:8080"
        timeout: 5
        method: GET
